### ISSUE TITLE
Interesting work! Could you provide instructions on how to change the dynamics on-the-fly?

### ISSUE THREAD

**Issue by xinleipan** [sunblaze-ucb/rl-generalization#4]
Thanks for providing this framework on gym environment to perturb the dynamics. In mujoco, we can easily change the dynamics on-the-fly, while it is not clear from the readme to me how we can create an environment, for example, "CartPole-v0" with a prespecified mass and length? Could you provide an example in the ReadMe? Thanks a lot!

**Comment by kxgao** [comment]
This functionality is not currently included. I think it can be done by inserting extra arguments into the init and reset functions. Following the format in **sunblaze_envs.classic_control**:
```python
class PredefinedCartPole(ModifiableCartPoleEnv):

    def __init__(self, force_mag=10.0, length=0.5, masspole=0.1):
        super(PredefinedCartPole, self).__init__()
        self.force_mag = force_mag
        self.length = length
        self.masspole = masspole
        self._followup()

    def reset(self, new=True, force_mag=10.0, length=0.5, masspole=0.1):
        self.nsteps = 0  # for super.is_success()
        self.state = self.np_random.uniform(low=-0.05, high=0.05, size=(4,))
        self.steps_beyond_done = None
        if new:
            self.force_mag = force_mag
            self.length = length
            self.masspole = masspole
            self._followup()
        return np.array(self.state)

    @property
    def parameters(self):
        parameters = super(PredefinedCartPole, self).parameters
        parameters.update({'force_mag': self.force_mag, 'length': self.length, 'masspole': self.masspole, 'total_mass': self.total_mass, 'polemass_length': self.polemass_length, })
        return parameters
```
Then we'd have to register the new environment in **sunblaze_envs.__init__**.

**Comment by xinleipan** [comment]
I tried this, but found that when I call the reset function, it actually does not have the argument "new". The error is what follows,

    _ = env.reset(new=True)
    Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        TypeError: reset() got an unexpected keyword argument 'new'

I checked the type of env, and it is:

        type(env)
        <class 'sunblaze_envs.time_limit.TimeLimit'>

not the expected classical_control?

**Comment by kxgao** [comment]
Sorry for the late reply! The argument 'new' was created for the adaptive algorithm only, where the environment parameters are not always regenerated at the end of each episode. If you want to sample new environment parameters at the end of each episode, do as you did before but use env.reset() instead of env.reset(new=True). If you want the option of keeping the environment the same at the end of an episode, use env.reset(new=True/False) and the files in in examples.adaptive (see examples.adaptive.train for an example of how to set up the environment).
