### ISSUE TITLE
TypeError: reset() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by LucasAlegre** [sunblaze-ucb/rl-generalization#5]
Hi,

I'm getting the following error message running:
  File "/home/lucas/Desktop/rl-generalization/sunblaze_envs/time_limit.py", line 10, in reset
    return self.env.reset(reset_params)
TypeError: reset() takes 1 positional argument but 2 were given

This happens only on Roboschool envs.

Any idea of why? I'm using the correct gym version (0.10.8).

Thanks!

**Comment by cpacker** [comment]
Would you mind pasting the exact command you're using + full output / stack trace + output of `pip list`?

Also, can you try using the docker container? I just ran PPO + SunblazeHalfCheetah using the docker container via the instructions on the README and it seems to work fine.

**Comment by LucasAlegre** [comment]
Hi,

The code is simply:

```
import gym
import roboschool
import sunblaze_envs
env = sunblaze_envs.make('SunblazeHopper-v0')
obs = env.reset()
for i in range(10000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(env.action_space.sample())
    env.render()
```

The full output is:
```
Traceback (most recent call last):
  File "experiments/a2c_hopper.py", line 49, in <module>
    obs = env.reset()
  File "/home/lucas/Desktop/rl-generalization/sunblaze_envs/time_limit.py", line 10, in reset
    return self.env.reset(reset_params)
TypeError: reset() takes 1 positional argument but 2 were given
```

It worked fine with the docker container. However, I really want to understand what is making this error on my virtualenv.

Thanks!

**Comment by cpacker** [comment]
Glad to hear it's working in the container.

The envs and env wrappers classes in sunblaze_envs take an extra reset argument (to accommodate the trials and episodes setup for adaptive methods - eg see https://github.com/sunblaze-ucb/rl-generalization/blob/5e05aa108aeadd4cf21f45d56128e9da3bddc14c/sunblaze_envs/classic_control.py#L53 and https://github.com/sunblaze-ucb/rl-generalization/blob/5e05aa108aeadd4cf21f45d56128e9da3bddc14c/sunblaze_envs/time_limit.py#L5). The env object that's throwing a type error isn't accepting the extra `reset_params` args, so to debug start by checking what class `self.env` is.

**Comment by LucasAlegre** [comment]
The problemas was with roboschool version. I had to install version 1.0 to make it work. 
It would be cool if you supported the newer version of roboschool also.

Thanks!

**Comment by pokaxpoka** [comment]
@LucasAlegre @cpacker  Could you let me know the version of roboschool to handle this issue? (I tried 1.0.40 but have the same issue)

**Comment by LucasAlegre** [comment]
> @LucasAlegre @cpacker Could you let me know the version of roboschool to handle this issue? (I tried 1.0.40 but have the same issue)

Sorry for the late reply, the version was the first one (1.0.1).
