### ISSUE TITLE
How to add new environment?

### ISSUE THREAD

**Issue by YK-Jiang** [sunblaze-ucb/rl-generalization#9]
Thank you for such great project for testing the generalization in RL. Could you provide instructions on how to add new environment from mujoco such as Walker and Swimmer?

**Comment by kxgao** [comment]
Currently there is no way to add new environments from Mujoco, the code is only compatible with Roboschool. I suggest this repo if you're restricted to Mujoco: https://github.com/dennisl88/rand_param_envs. It also generates environments with randomized parameter values.
